<a href="https://colab.research.google.com/github/vaibhavkatex/The-Internship-2026/blob/main/Session__16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns

In [1]:
# uploading a Dataset
from google.colab import files
Uploaded = files.upload()

Saving insurance.csv to insurance.csv

**Q1. Load the insurance dataset using pandas and display the first 10 rows of the
data.**

In [6]:
df = pd.read_csv("insurance.csv")
df

      age     sex   bmi  children smoker     region  expenses
0      19  female  27.9         0    yes  southwest  16884.92
1      18    male  33.8         1     no  southeast   1725.55
2      28    male  33.0         3     no  southeast   4449.46
3      33    male  22.7         0     no  northwest  21984.47
4      32    male  28.9         0     no  northwest   3866.86
...   ...     ...   ...       ...    ...        ...       ...
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

[1338 rows x 7 columns]

In [9]:
f_10 = df.head(10)
f_10

   age     sex   bmi  children smoker     region  expenses
0   19  female  27.9         0    yes  southwest  16884.92
1   18    male  33.8         1     no  southeast   1725.55
2   28    male  33.0         3     no  southeast   4449.46
3   33    male  22.7         0     no  northwest  21984.47
4   32    male  28.9         0     no  northwest   3866.86
5   31  female  25.7         0     no  southeast   3756.62
6   46  female  33.4         1     no  southeast   8240.59
7   37  female  27.7         3     no  northwest   7281.51
8   37    male  29.8         2     no  northeast   6406.41
9   60  female  25.8         0     no  northwest  28923.14

**Q2. Use pandas functions to get basic information about the dataset:
Shape of the data (shape)
Column names and data types (info())
Statistical summary of numerical columns (describe())**

In [10]:
# Shape
df.shape

(1338, 7)

In [15]:
# Column names and data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   expenses  1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [16]:
# Statistical summary of numerical columns
df.describe()

               age          bmi     children      expenses
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.665471     1.094918  13270.422414
std      14.049960     6.098382     1.205493  12110.011240
min      18.000000    16.000000     0.000000   1121.870000
25%      27.000000    26.300000     0.000000   4740.287500
50%      39.000000    30.400000     1.000000   9382.030000
75%      51.000000    34.700000     2.000000  16639.915000
max      64.000000    53.100000     5.000000  63770.430000

**Q3. Check if the dataset contains any null/missing values. Show the count of null
values for each column.**

In [24]:
# Check null values in each column
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
expenses    0
dtype: int64

**Q4. Identify numerical and categorical columns in the dataset. Print them
separately.**

In [29]:
# Identify numerical columns
numerical_columns = df.select_dtypes(include=['int64', 'float64']).columns
print("numerical columns :",numerical_columns)

# Identify categorical columns
categorical_columns = df.select_dtypes(include=['object']).columns
print(" categorical columns :",categorical_columns)

numerical columns : Index(['age', 'bmi', 'children', 'expenses'], dtype='object')
 categorical columns : Index(['sex', 'smoker', 'region'], dtype='object')

**Q5. Create distribution plots for all numerical columns (age, bmi, children,
charges):
Use sns.histplot() or sns.distplot()
Create one plot per column (total 4 plots)
Add meaningful titles and labels***